pastes/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^paste/(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})$', view_paste, name='paste'),
    url(r'^paste/(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/raw$', view_raw_paste, name='rawpaste'),
    url(r'^blob/(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})$', view_file, name='viewfile'),
    url(r'^blob/(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/download$', download_file, name='download'),
    url(r'^api/upload', api_upload, name='apiupload'),
]

app_name = 'pastes'

pastes/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
import pygments
from pygments import highlight
from pygments.lexers import get_lexer_by_name, get_lexer_for_filename
from pygments.formatters import HtmlFormatter
import uuid

# Create your models here.
class TextUploadManager(models.Manager):
    def create_text(self, text, language="", filename=None):
        textupload = self.create(text=text, language=language, filename=filename)
        textupload.update_cache()
        return textupload


class TextUpload(models.Model):
    text = models.TextField()
    text_cache = models.TextField(blank=True, null=True)
    language = models.CharField(blank=True, null=True, max_length=64)
    filename = models.CharField(blank=True, null=True, max_length=256)
    creation = models.DateTimeField(default=timezone.now)
    uuid = models.UUIDField(editable=False, unique=True, default=uuid.uuid4)
    
    objects = TextUploadManager()

    def update_cache(self):
        try:
            if self.language == "" and self.filename is not None:
                lexer = get_lexer_for_filename(self.filename, stripall=True)
            else:
                lexer = get_lexer_by_name(self.language, stripall=True)
        except pygments.util.ClassNotFound:
            lexer = get_lexer_by_name("text")

        self.text_cache = highlight(self.text, lexer, HtmlFormatter(linenos=True))

    def get_html(self):
        if self.text_cache is None:
            self.update_cache()
        return self.text_cache

    def __str__(self):
        return self.filename or str(self.uuid)

    def get_absolute_url(self):
        return reverse('pastes:paste', kwargs={'uuid': self.uuid})


def get_file_path(instance, filename):
    if len(filename.split('.')) != 1:
        ext = '.' + filename.split('.')[-1]
        f = ".".join(filename.split('.')[:-1])
    else:
        ext = ''
        f = filename
    # TODO: Use instance's uuid
    return f + ':' + str(uuid.uuid4()) + ext

class FileUpload(models.Model):
    title = models.CharField(max_length=256, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    creation = models.DateTimeField(default=timezone.now)
    uuid = models.UUIDField(editable=False, unique=True, default=uuid.uuid4)
    
    file = models.FileField(upload_to=get_file_path)

    def __str__(self):
        return self.title or str(self.uuid)
    
    def get_absolute_url(self):
        return reverse('pastes:viewfile', kwargs={'uuid': self.uuid})

    def get_original_file(self):
        if len(self.file.name.split('.')) != 1:
            ext = '.' + self.file.name.split('.')[-1]
        else:
            ext = ''
        return ":".join(self.file.name.split(':')[:-1]) + ext

    def get_download_name(self):
        if ".".join(self.get_original_file().split(".")[:-1]) != "":
            return self.get_original_file()
        if self.title.strip() != "":
            if len(self.file.name.split('.')) != 1:
                ext = '.' + self.file.name.split('.')[-1]
            else:
                ext = ''
            return self.title.lower().replace(" ", "-") + ext
        return self.file.name

pastes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from .models import *
from sendfile import sendfile
import mimetypes

# Create your views here.
def home(request):
    pastes = TextUpload.objects.all().order_by('-creation')[:50]
    return render(request, 'pastes/home.html', {'pastes': pastes})


def view_paste(request, uuid):
    paste = get_object_or_404(TextUpload, uuid=uuid)
    return render(request, 'pastes/paste.html', {'paste': paste})


def view_raw_paste(request, uuid):
    paste = get_object_or_404(TextUpload, uuid=uuid)
    return HttpResponse(paste.text, content_type='text/text')

def view_file(request, uuid):
    file = get_object_or_404(FileUpload, uuid=uuid)
    mime = mimetypes.guess_type(file.file.path)

    if mime[0] is not None:
        typecat = mime[0].split('/')[0]
    else:
        typecat = 'none'
    if mime[1] is not None:
        return render(request, 'pastes/file.html', {'file': file, 'mime': mime})
    mime = typecat
    if typecat == 'image':
        return render(request, 'pastes/image.html', {'file': file, 'mime': mime})
    elif typecat == 'video':
        return render(request, 'pastes/video.html', {'file': file, 'mime': mime})
    elif typecat == 'audio':
        return render(request, 'pastes/audio.html', {'file': file, 'mime': mime})
    else:
        return render(request, 'pastes/file.html', {'file': file, 'mime': mime})

def download_file(request, uuid):
    file = get_object_or_404(FileUpload, uuid=uuid)
    return sendfile(request, file.file.path, attachment=True, attachment_filename=file.get_download_name())

# API
@csrf_exempt
def api_upload(request):
    errors = []
    if request.method != 'POST':
        return JsonResponse({"errors":["Must use POST"]}, status=400)

    if request.META.get('Authorization', request.POST.get('token', '')) != getattr(settings, "API_TOKEN", ''):
        errors.append("Invalid auth token")

    if 'file' not in request.FILES:
        errors.append("`file' not sent")

    if errors:
        return JsonResponse({"errors":errors}, status=400)
    else:
        mime = mimetypes.guess_type(request.FILES['file'].name)
        if mime[0] is not None and mime[0].startswith('text/') and mime[1] is None:
            text = request.FILES['file'].read()
            t = TextUpload.objects.create_text(text, filename=request.FILES['file'].name)
            t.save()
        else:
            t = FileUpload(file=request.FILES['file'], title=request.POST.get('title', request.FILES['file'].name), description=request.POST.get('description', ''))
            t.save()
        return JsonResponse({'errors': errors, 'url': t.get_absolute_url()})

pastes/templates/pastes/audio.html
{% extends "pastes/file.html" %}
{% block media %}
<div>
<audio src="{{ file.file.url }}" controls></audio>
</div>
{% endblock %}

pastes/templates/pastes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} | Pastes</title>
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'pastes/main.css' %}">
    {% block extrastyle %}

    {% endblock %}
</head>
<body>
    {% block body %}
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
    {% endblock %}
</body>
</html>

pastes/templates/pastes/file.html
{% extends "pastes/base.html" %}
{% block title %}{{ file }}{% endblock %}
{% block content %}
<header>
    <div class="date">{{ file.creation|date:"M dS, Y, h:i A" }}</div>
    {% if file.title %}
    <h2>{{ file.title }}</h2>
    {% else %}
    <h2>Unnamed file</h2>
    {% endif %}
</header>
<div class="center">
    {% block media %}
        <p>No preview available for type {{ mime }}</p>
    {% endblock %}
    <a href="{% url 'pastes:download' file.uuid %}">Download {{ file.get_download_name }}</a>
</div>
{% if file.description %}
<h3>Description</h3>
<p class="description">
    {{ file.description|linebreaks }}
</p>
{% endif %}
{% endblock %}

pastes/templates/pastes/home.html
{% extends "pastes/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<h1>pta2002's pastes</h1>
<ul class="pastes">
    {% for paste in pastes %}
    <li class="paste"><a href="{% url 'pastes:paste' paste.uuid %}"><strong>{{ paste }}</strong> ({% if paste.language %}{{ paste.language }}, {% endif %}Created at {{ paste.creation|date:"M dS, Y, h:i A" }})</a></li>
    {% endfor %}
</ul>
{% endblock %}

pastes/templates/pastes/image.html
{% extends "pastes/file.html" %}
{% block media %}
<div>
    <img src="{{ file.file.url }}" alt="{{ file }}">
</div>
{% endblock %}

pastes/templates/pastes/paste.html
{% extends "pastes/base.html" %}
{% block title %}{{ paste }}{% endblock %}

{% block extrastyle %}
{% load static %}
<link rel="stylesheet" href="{% static 'pastes/monokai.css' %}">
{% endblock %}

{% block content %}
<header>
    <div class="date">{{ paste.creation|date:"M dS, Y, h:i A" }} - <a href="{% url 'pastes:rawpaste' paste.uuid %}">Raw</a></div>
{% if paste.filename %}
<h2>{{ paste.filename }}</h2>
{% else %}
<h2>Unnamed paste</h2>
{% endif %}
</header>
{{ paste.get_html|safe }}
{% endblock %}

pastes/templates/pastes/video.html
{% extends "pastes/file.html" %}
{% block media %}
<div>
    <video controls name="media">
        <source src="{{ file.file.url }}" type="{{ mime }}">
    </video>
</div>
{% endblock %}